// Embedded Python source code for the workshop_helpers package.
//
// These constants are written to a temporary directory at runtime so the
// Python sandbox process can import them via:
//   import workshop_helpers.geometry
//   from workshop_helpers.sheetmetal import bend_allowance
// ignore_for_file: prefer_single_quotes

const String kWorkshopHelpersInit =
    '# workshop_helpers package\n'
    '# Bundled helper modules for Workshop Helper calculators.\n'
    '# Import sub-modules explicitly, e.g.:\n'
    '#   from workshop_helpers.geometry import bend_allowance\n';

const String kGeometryPy =
    '"""\n'
    'Workshop Helpers - geometry.py\n'
    '\n'
    'Common geometry calculations used in fabrication and machining.\n'
    '\n'
    'Usage example:\n'
    '    from workshop_helpers.geometry import circle_area, bend_allowance\n'
    '    area = circle_area(diameter=50.0)\n'
    '    ba   = bend_allowance(thickness=2.0, angle_deg=90, radius=3.0)\n'
    '"""\n'
    'import math\n'
    '\n'
    '\n'
    'def circle_area(diameter):\n'
    '    """Return the area of a circle given its diameter."""\n'
    '    return math.pi * (diameter / 2.0) ** 2\n'
    '\n'
    '\n'
    'def circle_circumference(diameter):\n'
    '    """Return the circumference of a circle given its diameter."""\n'
    '    return math.pi * diameter\n'
    '\n'
    '\n'
    'def circle_diameter_from_area(area):\n'
    '    """Return the diameter of a circle given its area."""\n'
    '    return 2.0 * math.sqrt(area / math.pi)\n'
    '\n'
    '\n'
    'def rectangle_area(width, height):\n'
    '    """Return the area of a rectangle."""\n'
    '    return width * height\n'
    '\n'
    '\n'
    'def rectangle_perimeter(width, height):\n'
    '    """Return the perimeter of a rectangle."""\n'
    '    return 2.0 * (width + height)\n'
    '\n'
    '\n'
    'def triangle_area_base_height(base, height):\n'
    '    """Return the area of a triangle given base and perpendicular height."""\n'
    '    return 0.5 * base * height\n'
    '\n'
    '\n'
    'def hypotenuse(a, b):\n'
    '    """Return the hypotenuse of a right triangle with legs a and b."""\n'
    '    return math.sqrt(a ** 2 + b ** 2)\n'
    '\n'
    '\n'
    'def bend_allowance(thickness, angle_deg, radius, k_factor=0.33):\n'
    '    """\n'
    '    Calculate the flat-blank length consumed by a bend (bend allowance).\n'
    '\n'
    '    Parameters\n'
    '    ----------\n'
    '    thickness  : material thickness\n'
    '    angle_deg  : interior bend angle in degrees\n'
    '    radius     : inside bend radius\n'
    '    k_factor   : neutral-axis ratio (default 0.33, range 0.25-0.50)\n'
    '    """\n'
    '    angle_rad = math.radians(angle_deg)\n'
    '    return angle_rad * (radius + k_factor * thickness)\n'
    '\n'
    '\n'
    'def bend_deduction(thickness, angle_deg, radius, k_factor=0.33):\n'
    '    """Calculate bend deduction."""\n'
    '    ba = bend_allowance(thickness, angle_deg, radius, k_factor)\n'
    '    outside_setback = math.tan(math.radians(angle_deg / 2.0)) * (radius + thickness)\n'
    '    return 2.0 * outside_setback - ba\n'
    '\n'
    '\n'
    'def flat_blank_length(flange_a, flange_b, thickness, angle_deg, radius, k_factor=0.33):\n'
    '    """\n'
    '    Return the total flat-blank length for a single-bend part.\n'
    '\n'
    '    Parameters\n'
    '    ----------\n'
    '    flange_a   : length of the first flange (outside dimension)\n'
    '    flange_b   : length of the second flange (outside dimension)\n'
    '    thickness  : material thickness\n'
    '    angle_deg  : interior bend angle in degrees\n'
    '    radius     : inside bend radius\n'
    '    k_factor   : neutral-axis ratio (default 0.33)\n'
    '    """\n'
    '    bd = bend_deduction(thickness, angle_deg, radius, k_factor)\n'
    '    return flange_a + flange_b - bd\n'
    '\n'
    '\n'
    'def deg_to_rad(degrees):\n'
    '    """Convert degrees to radians."""\n'
    '    return math.radians(degrees)\n'
    '\n'
    '\n'
    'def rad_to_deg(radians):\n'
    '    """Convert radians to degrees."""\n'
    '    return math.degrees(radians)\n';

const String kSheetmetalPy =
    '"""\n'
    'Workshop Helpers - sheetmetal.py\n'
    '\n'
    'Sheet metal specific calculations including material weights, corner reliefs,\n'
    'press brake tonnage estimates, and developed lengths.\n'
    '\n'
    'Usage example:\n'
    '    from workshop_helpers.sheetmetal import material_weight, press_brake_tonnage\n'
    '    kg   = material_weight(length_mm=1000, width_mm=500, thickness_mm=3.0)\n'
    '    tons = press_brake_tonnage(thickness_mm=3.0, bend_length_mm=1000)\n'
    '"""\n'
    'import math\n'
    '\n'
    '\n'
    'DENSITIES_KG_M3 = {\n'
    '    "steel":      7850.0,\n'
    '    "stainless":  8000.0,\n'
    '    "aluminium":  2700.0,\n'
    '    "aluminum":   2700.0,\n'
    '    "copper":     8960.0,\n'
    '    "brass":      8500.0,\n'
    '    "titanium":   4510.0,\n'
    '}\n'
    '\n'
    '\n'
    'def material_weight(length_mm, width_mm, thickness_mm, density_kg_m3=7850.0):\n'
    '    """\n'
    '    Return the weight (kg) of a rectangular plate.\n'
    '\n'
    '    Parameters\n'
    '    ----------\n'
    '    length_mm       : plate length in millimetres\n'
    '    width_mm        : plate width in millimetres\n'
    '    thickness_mm    : plate thickness in millimetres\n'
    '    density_kg_m3   : material density in kg/m3 (default: mild steel 7850)\n'
    '    """\n'
    '    volume_m3 = (length_mm / 1000.0) * (width_mm / 1000.0) * (thickness_mm / 1000.0)\n'
    '    return volume_m3 * density_kg_m3\n'
    '\n'
    '\n'
    'def material_weight_named(length_mm, width_mm, thickness_mm, material="steel"):\n'
    '    """\n'
    '    Return the weight (kg) using a named material density.\n'
    '\n'
    '    Supported materials: steel, stainless, aluminium, aluminum,\n'
    '                         copper, brass, titanium.\n'
    '    """\n'
    '    key = material.lower()\n'
    '    if key not in DENSITIES_KG_M3:\n'
    '        raise ValueError(\n'
    '            f"Unknown material \'{material}\'. "\n'
    '            f"Use one of: {\', \'.join(DENSITIES_KG_M3)}"\n'
    '        )\n'
    '    return material_weight(length_mm, width_mm, thickness_mm, DENSITIES_KG_M3[key])\n'
    '\n'
    '\n'
    'def press_brake_tonnage(thickness_mm, bend_length_mm,\n'
    '                        tensile_strength_mpa=450.0, die_opening_mm=None):\n'
    '    """\n'
    '    Estimate press brake tonnage for an air-bend.\n'
    '\n'
    '    Parameters\n'
    '    ----------\n'
    '    thickness_mm         : material thickness in mm\n'
    '    bend_length_mm       : bend length in mm\n'
    '    tensile_strength_mpa : material UTS in MPa (default 450 for mild steel)\n'
    '    die_opening_mm       : die opening in mm (default 8 x thickness)\n'
    '\n'
    '    Returns\n'
    '    -------\n'
    '    float : estimated force in kN\n'
    '    """\n'
    '    if die_opening_mm is None:\n'
    '        die_opening_mm = 8.0 * thickness_mm\n'
    '    if die_opening_mm <= 0:\n'
    '        raise ValueError("die_opening_mm must be positive.")\n'
    '    return (1.33 * thickness_mm ** 2 * bend_length_mm * tensile_strength_mpa) / (die_opening_mm * 1000.0)\n'
    '\n'
    '\n'
    'def corner_relief_radius(thickness_mm, factor=1.5):\n'
    '    """\n'
    '    Return a recommended corner-relief hole radius.\n'
    '\n'
    '    Parameters\n'
    '    ----------\n'
    '    thickness_mm : material thickness in mm\n'
    '    factor       : multiplier (default 1.5 - industry rule of thumb)\n'
    '    """\n'
    '    return thickness_mm * factor\n'
    '\n'
    '\n'
    'def cylinder_developed_length(outer_diameter_mm):\n'
    '    """\n'
    '    Return the flat-blank length required to roll a full cylinder.\n'
    '\n'
    '    DL = pi x OD  (valid when wall thickness << OD)\n'
    '    """\n'
    '    return math.pi * outer_diameter_mm\n';

const String kLookupTablesPy =
    '"""\n'
    'Workshop Helpers - lookup_tables.py\n'
    '\n'
    'Utility functions for working with discrete lookup tables, including\n'
    'linear interpolation and nearest-value search.\n'
    '\n'
    'Usage example:\n'
    '    from workshop_helpers.lookup_tables import interpolate, nearest_value\n'
    '\n'
    '    thread_pitch = [\n'
    '        (3, 0.5), (4, 0.7), (5, 0.8), (6, 1.0),\n'
    '        (8, 1.25), (10, 1.5), (12, 1.75),\n'
    '    ]\n'
    '    pitch = interpolate(thread_pitch, 7)    # 1.125 (interpolated)\n'
    '    pitch = nearest_value(thread_pitch, 7)  # 1.25  (M8 nearest)\n'
    '"""\n'
    '\n'
    '\n'
    'def interpolate(table, input_value):\n'
    '    """\n'
    '    Linearly interpolate from a list of (input, output) tuples.\n'
    '\n'
    '    The table must be sorted in ascending order of the input column.\n'
    '    Values outside the range are clamped to the boundary output.\n'
    '    """\n'
    '    if not table:\n'
    '        raise ValueError("Lookup table is empty.")\n'
    '    sorted_table = sorted(table, key=lambda row: row[0])\n'
    '    if input_value <= sorted_table[0][0]:\n'
    '        return float(sorted_table[0][1])\n'
    '    if input_value >= sorted_table[-1][0]:\n'
    '        return float(sorted_table[-1][1])\n'
    '    for i in range(len(sorted_table) - 1):\n'
    '        x0, y0 = sorted_table[i]\n'
    '        x1, y1 = sorted_table[i + 1]\n'
    '        if x0 <= input_value <= x1:\n'
    '            t = (input_value - x0) / (x1 - x0)\n'
    '            return float(y0 + t * (y1 - y0))\n'
    '    return float(sorted_table[-1][1])\n'
    '\n'
    '\n'
    'def nearest_value(table, input_value):\n'
    '    """\n'
    '    Return the output whose input is closest to input_value.\n'
    '    """\n'
    '    if not table:\n'
    '        raise ValueError("Lookup table is empty.")\n'
    '    closest_row = min(table, key=lambda row: abs(row[0] - input_value))\n'
    '    return float(closest_row[1])\n'
    '\n'
    '\n'
    'def lookup_exact(table, input_value, tolerance=1e-9):\n'
    '    """\n'
    '    Return the output for an exact match, or None if not found.\n'
    '    """\n'
    '    for x, y in table:\n'
    '        if abs(x - input_value) <= tolerance:\n'
    '            return float(y)\n'
    '    return None\n';
